// Generated by Wrangler on Sat Aug 03 2024 00:58:39 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DB: D1Database;
}
